export default [
  { "iconSrc": "https://raw.githubusercontent.com/devicons/devicon/master/icons/typescript/typescript-plain.svg", "name": "typescript" },
  { "iconSrc": "https://raw.githubusercontent.com/devicons/devicon/master/icons/react/react-original.svg", "name": "react" },
  { "iconSrc": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg", "name": "nextjs" },
  { "iconSrc": "https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-plain.svg", "name": "javascript" },
  { "iconSrc": "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/tailwindcss/tailwindcss-original.svg", "name": "tailwindcss" },
  { "iconSrc": "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/materialui/materialui-original.svg", "name": "materialui" },
  { "iconSrc": "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/vitejs/vitejs-original.svg", "name": "vitejs" },
  { "iconSrc": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg", "name": "nodejs" },
  { "iconSrc": "https://raw.githubusercontent.com/devicons/devicon/master/icons/postgresql/postgresql-plain.svg", "name": "postgresql" },
  { "iconSrc": "https://raw.githubusercontent.com/devicons/devicon/master/icons/docker/docker-plain.svg", "name": "docker" },
  { "iconSrc": "https://raw.githubusercontent.com/devicons/devicon/master/icons/vscode/vscode-original.svg", "name": "vscode" },
  { "iconSrc": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-plain.svg", "name": "git" },
  { "iconSrc": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/figma/figma-original.svg", "name": "figma" },
  { "iconSrc": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sass/sass-original.svg", "name": "sass" },
  { "iconSrc": "https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original.svg", "name": "html5" },
  { "iconSrc": "https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original.svg", "name": "css3" },
  { "iconSrc": "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/reactrouter/reactrouter-original.svg", "name": "react-router" },
  { "iconSrc": "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/amazonwebservices/amazonwebservices-plain-wordmark.svg", "name": "aws" }
]
